server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/internetshop
    username: root
    password: uhbujhbq
    driver-class-name: com.mysql.jdbc.Driver
jpa:
    database: MYSQL